/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/**
 *
 * @author T-107
 */
public class PresentacionTest extends javax.swing.JFrame {

    /**
     * Creates new form PresentacionTest
     */
    JRadioButton radios[];
    Opcion []opciones;
    Pregunta p1;
    
    public PresentacionTest() {
        initComponents();
        setLocationRelativeTo(this);
        
        //Generamos en un arreglo los radios button visuales
        radios=new JRadioButton[5];
        opciones=new Opcion[5];
        radios[0]=radioOp1;
        radios[1]=radioOp2;
        radios[2]=radioOp3;
        radios[3]=radioOp4;
        radios[4]=radioOp5;
        
        //Llenamos el modelo con los valores correctos en la interfaz de usuario
        Opcion op1=new Opcion("quesadillas", false);
       //System.out.println("Tu titulo es "+op1.titulo); 
        //System.out.println("Es correcta" +op1.correcta);  
       
        Opcion op2=new Opcion("La grasa", true);
         Opcion op3=new Opcion("El Sol", false);
          Opcion op4=new Opcion("La contaminacion", false);
           Opcion op5=new Opcion("La Sal", false);
           
           
           //Se crean los arreglos asi, los []van primero. 
            opciones[0]=op1;
            opciones[1]=op2;
            opciones[2]=op3;
            opciones[3]=op4;
            opciones[4]=op5;
           
           
           //Para hacer la pregunta, "Primero es de tipo String", el segundo de Tipo Arreglo.
           p1=new Pregunta("Este es la principal causa del Cancer",opciones);
           
           etiquetaTitulo.setText(p1.titulo);
        for(int i=0;i<radios.length;i++){
            radios[i].setText(p1.opciones[i].titulo);
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        etiquetaTitulo = new javax.swing.JLabel();
        radioOp1 = new javax.swing.JRadioButton();
        radioOp2 = new javax.swing.JRadioButton();
        radioOp3 = new javax.swing.JRadioButton();
        radioOp4 = new javax.swing.JRadioButton();
        radioOp5 = new javax.swing.JRadioButton();
        checarRespuesta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        etiquetaTitulo.setText("jLabel1");

        buttonGroup1.add(radioOp1);
        radioOp1.setText("jRadioButton1");

        buttonGroup1.add(radioOp2);
        radioOp2.setText("jRadioButton2");

        buttonGroup1.add(radioOp3);
        radioOp3.setText("jRadioButton3");

        buttonGroup1.add(radioOp4);
        radioOp4.setText("jRadioButton4");

        buttonGroup1.add(radioOp5);
        radioOp5.setText("jRadioButton5");

        checarRespuesta.setText("Checar Respuesta");
        checarRespuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checarRespuestaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(etiquetaTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioOp2)
                            .addComponent(radioOp1)
                            .addComponent(radioOp3)
                            .addComponent(radioOp4)
                            .addComponent(radioOp5))))
                .addContainerGap(86, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(checarRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(etiquetaTitulo)
                .addGap(28, 28, 28)
                .addComponent(radioOp1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioOp2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioOp3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioOp4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioOp5)
                .addGap(18, 18, 18)
                .addComponent(checarRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checarRespuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checarRespuestaActionPerformed
        // TODO add your handling code here:
        
//Buscamos el radioButton seleccionado
        
        int indiceSeleccionado=0;
        for(int i=0;i<radios.length;i++){
            if(radios[i].isSelected()){
                indiceSeleccionado=i;
                break;
               
            }
        }
        
        
       JOptionPane.showConfirmDialog(this,""+evaluar(p1,radios[indiceSeleccionado]));
    }//GEN-LAST:event_checarRespuestaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PresentacionTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PresentacionTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PresentacionTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PresentacionTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PresentacionTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton checarRespuesta;
    private javax.swing.JLabel etiquetaTitulo;
    private javax.swing.JRadioButton radioOp1;
    private javax.swing.JRadioButton radioOp2;
    private javax.swing.JRadioButton radioOp3;
    private javax.swing.JRadioButton radioOp4;
    private javax.swing.JRadioButton radioOp5;
    // End of variables declaration//GEN-END:variables

public boolean evaluar(Pregunta p,JRadioButton r){
    boolean correcta=false;
    //Que logica se pondría??
    for(int i=0;i<p.opciones.length;i++){
        if(opciones[i].titulo.equals(r.getText())){
            if(p1.opciones[i].correcta){
            correcta=true;
            break;
            }
        }
    }
    
    
    return correcta;
}


}
