/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/**
 *
 * @author T-107
 */
public class TestExamen extends javax.swing.JFrame {

    /**
     * Creates new form TestExamen
     */
    
    JRadioButton radios[];
    Opcion []opciones;
    Pregunta p1;
    Pregunta p2;
    
    
    public TestExamen() {
        initComponents();
        setLocationRelativeTo(this);
        siguiente.setEnabled(false);
        
        
        //Generamos en un arreglo los radios button visuales
        radios=new JRadioButton[4];
        opciones=new Opcion[4];
        radios[0]=radioOp1;
        radios[1]=radioOp2;
        radios[2]=radioOp3;
        radios[3]=radioOp4;
        
        
        //Llenamos el modelo con los valores correctos en la interfaz de usuario
        Opcion op1=new Opcion("El Popocatepelt", false);
       //System.out.println("Tu titulo es "+op1.titulo); 
        //System.out.println("Es correcta" +op1.correcta);  
       
        Opcion op2=new Opcion("El Everest", true);
        Opcion op3=new Opcion("El Aconcagua", false);
        Opcion op4=new Opcion("El Pico de Orizaba", false);
           
           
           
           //Se crean los arreglos asi, los []van primero. 
            opciones[0]=op1;
            opciones[1]=op2;
            opciones[2]=op3;
            opciones[3]=op4;
            
           
           //Para hacer la pregunta, "Primero es de tipo String", el segundo de Tipo Arreglo.
           p1=new Pregunta("¿Cual es la montaña más alta del mundo",opciones);
           
           etiquetaTitulo.setText(p1.titulo);
        for(int i=0;i<radios.length;i++){
            radios[i].setText(p1.opciones[i].titulo);
        }
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void checarRespuestaActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
        
//Buscamos el radioButton seleccionado
        
        int indiceSeleccionado=0;
        for(int i=0;i<radios.length;i++){
            if(radios[i].isSelected()){
                indiceSeleccionado=i;
                break;
               
            }
        }
        
        System.out.println("El indice seleccionado es:"+indiceSeleccionado);
      JOptionPane.showConfirmDialog(this,""+evaluar(p1,indiceSeleccionado));
    }                                               

    private void radioOp1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        
    
    private void radioOp4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        etiquetaTitulo = new javax.swing.JLabel();
        checar = new javax.swing.JButton();
        siguiente = new javax.swing.JButton();
        radioOp1 = new javax.swing.JRadioButton();
        radioOp2 = new javax.swing.JRadioButton();
        radioOp3 = new javax.swing.JRadioButton();
        radioOp4 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        etiquetaTitulo.setText("jLabel1");

        checar.setText("Checar");
        checar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checarActionPerformed(evt);
            }
        });

        siguiente.setText("siguiente");
        siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteActionPerformed(evt);
            }
        });

        radioOp1.setText("jRadioButton1");

        radioOp2.setText("jRadioButton2");

        radioOp3.setText("jRadioButton3");

        radioOp4.setText("jRadioButton4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(checar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                .addComponent(siguiente)
                .addGap(48, 48, 48))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(radioOp2)
                            .addComponent(radioOp1)
                            .addComponent(radioOp3)
                            .addComponent(radioOp4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(etiquetaTitulo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(etiquetaTitulo)
                .addGap(42, 42, 42)
                .addComponent(radioOp1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioOp2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioOp3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioOp4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checar)
                    .addComponent(siguiente))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteActionPerformed
        // TODO add your handling code here:
        
        etiquetaTitulo.setText("Todos los siguientes estados tienen costas excepto");
        Opcion op1=new Opcion("El Popocatepelt", false);
       //System.out.println("Tu titulo es "+op1.titulo); 
        //System.out.println("Es correcta" +op1.correcta);  
       
        Opcion op2=new Opcion("El Everest", true);
        Opcion op3=new Opcion("El Aconcagua", false);
        Opcion op4=new Opcion("El Pico de Orizaba", false);
        
        siguiente.setEnabled(false);
        checar.setEnabled(true);
    }//GEN-LAST:event_siguienteActionPerformed

    private void checarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checarActionPerformed
        int indiceSeleccionado = 0;
        // TODO add your handling code here:
        
       //checar.JOptionPane.showConfirmDialog(this,""+evaluar(p1,indiceSeleccionado));
        //se deshabilita el boton checar y se habilita el boton siguiente
        checar.setEnabled(false);
        siguiente.setEnabled(true);
    }//GEN-LAST:event_checarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestExamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestExamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestExamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestExamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestExamen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton checar;
    private javax.swing.JLabel etiquetaTitulo;
    private javax.swing.JRadioButton radioOp1;
    private javax.swing.JRadioButton radioOp2;
    private javax.swing.JRadioButton radioOp3;
    private javax.swing.JRadioButton radioOp4;
    private javax.swing.JButton siguiente;
    // End of variables declaration//GEN-END:variables

public boolean evaluar(Pregunta p, int indiceSeleccionado){
boolean correcta=false;
if(p.opciones[indiceSeleccionado].correcta){
    correcta=true;
    
 }

return correcta;
}

}
